### ISSUE TITLE
Invalid Syntax in unipacker.py Line 73

### ISSUE THREAD

**Issue by Bhuvanamitra** [unipacker/unipacker#12]
When I run unipacker.py, I get Invalid Syntax Error in this line.

Line 73: ("End of unpacking stub:", f"0x{endaddr:02x}" if endaddr != sys.maxsize else "unknown"),

**Comment by Masrepus** [comment]
Are you using Python 3.6 or greater? Looks like your Python version doesn't support f-strings

**Comment by Bhuvanamitra** [comment]
I am using Python 2.7
What can I do to fix the problem? (preferrably not altering the python version)

**Comment by Masrepus** [comment]
Hm that's probably quite a bit of work, as we didn't develop unipacker with Python 2 support in mind

**Comment by Masrepus** [comment]
Unipacker now has a Dockerfile, so it can be run without having to touch your existing python installation. I hope this helps you

**Comment by Bhuvanamitra** [comment]
I have installed 3.6 and also installed all requirements. It is running now. But I get only one option shown when I start the Unipacker.
I start it with command python3.6 unipacker.py
![unpackerbug](https://user-images.githubusercontent.com/7961570/54805031-adbd0a80-4c9b-11e9-996f-c98b3e533477.png)

I give 0 and when asked for path of file I gave relative path to current directory. 
I get the following output which I am unable to infer. Please tell me what this is and what should be done to make it work properly.
TIA.
