### ISSUE TITLE
Showing only New Sample option

### ISSUE THREAD

**Issue by Bhuvanamitra** [unipacker/unipacker#13]
I have installed Python 3.6 and also installed all requirements. I ran the unpacker with command <python3.6 unipacker.py>
 I get only one option shown when I start the Unipacker.
I give 0 and when asked for path of file I gave relative path to current directory.
I get the following output from which I am unable to infer anything. Please tell me what this is and what should be done to make it work properly.
![unpackerbug](https://user-images.githubusercontent.com/7961570/54805947-992e4180-4c9e-11e9-861a-e8c5311d1a61.png)

TIA.

**Comment by vfsrfs** [comment]
We will take a look at it. It would be nice if you could provide the sample you are using, as a corrupted pe header could cause this behaviour.

Furthermore, please make sure, that you have the newest yara package installed, that supports the pe module [https://yara.readthedocs.io/en/v3.9.0/modules/pe.html](url).

**Comment by Masrepus** [comment]
Also please note that you need to install the dependencies for unipacker via the requirements.txt (```pip3 install -r requirements.txt```). One reason is that there is a Python module called "yara" which is actually not what we need, but rather you need to install "yara-python". The next reason is that we use a custom version of the unicorn engine, which is different from the one available on the normal pip repository.

**Comment by Bhuvanamitra** [comment]
Could not find a version that satisfies the requirement yara-python (from -r requirements.txt (line 2)) (from versions: )
No matching distribution found for yara-python (from -r requirements.txt (line 2))

This is what I get when using pip3.6 install -r requirements.txt

I am using yara 3.4.0

**Comment by Masrepus** [comment]
Are you on the latest commit from master? The requirements file has been fixed some days ago

**Comment by Bhuvanamitra** [comment]
Okay Masrepus, I will update and re-check.

**Comment by vfsrfs** [comment]
Also remember to uninstall the other yara package as it will create conflicts. You can do so by executing the following command: pip3.6 uninstall yara

**Comment by Bhuvanamitra** [comment]
Thank you Masrepus & vfsrfs, I have done that and started the unipacker.
But still i get only One option i.e, to choose New Sample..
![unipackerSingleOption](https://user-images.githubusercontent.com/7961570/54812788-fb447200-4cb1-11e9-8669-20545eeb2af3.png)

The pe support issue is solved though :+1: 
[8ff682.zip](https://github.com/unipacker/unipacker/files/2995799/8ff682.zip)
This is the file which is packed using UPX. I am trying to unpack that.

**Comment by vfsrfs** [comment]
You can start the unpacking with the r command. For more information about other commands use the help command or use the wiki

**Comment by Masrepus** [comment]
The "options" are actually history entries, so whenever you successfully opened a new sample file (i.e. you land in the shell, which is what you just got), this path is saved to the file ```.unpacker_history``` along with its identified packer. This is so that you don't have to re-enter the path again when you want to load this sample the next time.

**Comment by Bhuvanamitra** [comment]
Thanks for your quick responses. 
I have a doubt here, when you say 'code is emulated', does that mean it is executed in a sandbox?
What is the difference between emulation and execution in that case?
TIA.

**Comment by Masrepus** [comment]
We use unicorn engine for emulation. Unicorn provides us with a complete virtual x86 CPU setup. We can give it binary data (in this case a loaded .exe file) containing x86 assembly instructions and it will loop through it, behaving like a real CPU executing the code. The difference comes up whenever the code doesn't just use basic instructions but rather wants to call functions provided by Windows. At the core this is nothing different than calling an assembly subroutine, but the function is only available when the Windows binary loader links it to the appropriate kernel function.
As unipacker may run on a different OS than Windows, we don't have access to those Windows API functions. Thus we have to detect calls to them and use our own implementation (look at [apicalls.py](https://github.com/unipacker/unipacker/blob/5d61837f415dd9892aebe6978e60ae70e4f1f178/apicalls.py) for more details). This is where the emulation differs from execution: We fake Windows API calls, always considering that the implementation won't have the malicious effect on the host machine that the malware might have intended
