### ISSUE TITLE
Delete BP

### ISSUE THREAD

**Issue by crypto2011** [unipacker/unipacker#31]
Can you add ability to remove existing breakpoint(s)?

**Comment by Masrepus** [comment]
This is already available, just use the `del` command. Without further arguments, all existing breakpoints will be deleted, otherwise only those that you specify. Usage is the same as the `b` command

**Comment by Masrepus** [comment]
For further help on this or other topics you can check out our wiki: https://github.com/unipacker/unipacker/wiki
Unfortunately not all current features are described there yet, we are planning to update it at some point during the next weeks

**Comment by crypto2011** [comment]
Thanks

вт, 1 окт. 2019 г., 15:49 Samuel Hopstock <notifications@github.com>:
