### ISSUE TITLE
Error in file shell.py

### ISSUE THREAD

**Issue by crypto2011** [unipacker/unipacker#32]
I have error in file shell.py (line 251, print_imports). Really file has no imports, only sections UPX0, UPX1 and .rsrsc. Die reports that it is packed with UPX 3.03[NRV,best].

**Comment by Masrepus** [comment]
Seems to be fixed now in the dev branch

**Comment by Masrepus** [comment]
Has been merged into master after the tests were passing

**Comment by crypto2011** [comment]
Strange, but installator don't see pyreadline (were installed before for previous versions of unipacker).

**Comment by Masrepus** [comment]
Yes, cmd2 version needs to be downgraded, as we detected some breaking changes. Also, the fix for you problem hasn't been pushed to PyPi yet, so you should try cloning the repo and installing with `python3 setup.py install`
