### ISSUE TITLE
RESTful API for Unipacker

### ISSUE THREAD

**Issue by rpgeeganage** [unipacker/unipacker#43]
Hi, this is not about an issue.
I came to know about this wonderful project while I was looking into malware unpackers.
So, I wrote a RESTful API interface for your project using Docker.
This is my repo: [https://github.com/rpgeeganage/restful4up](https://github.com/rpgeeganage/restful4up)
I hope it will help this awesome project.

**Comment by Masrepus** [comment]
Hey that looks like a cool wrapper for people that want to offload the unpacking process to some external server, thanks for creating this! I'll add a link to our readme so that interested people can check it out

**Comment by rpgeeganage** [comment]
@Masrepus ,
Thanks a lot. I'll add more features such as view logs.

**Comment by Masrepus** [comment]
Great, we'll surely keep an eye on it!
