### ISSUE TITLE
Completed item still waiting:no extractable files found at:/path/

### ISSUE THREAD

**Issue by JimmyBringus** [unipacker/unipacker#55]
Hello,

I'm having an issue with my unpackerr configuration. First, I'll post the compose.yml I'm using for docker compose:

    unpackerr:
    container_name: unpackerr
    user: 1000:1000
    image: golift/unpackerr
    environment:
      - TZ= America/New York
      # General config
      - UN_DEBUG=false
      - UN_LOG_FILE=
      - UN_LOG_FILES=10
      - UN_LOG_FILE_MB=10
      - UN_INTERVAL=2m
      - UN_START_DELAY=1m
      - UN_RETRY_DELAY=5m
      - UN_MAX_RETRIES=3
      - UN_PARALLEL=1
      - UN_FILE_MODE=0644
      - UN_DIR_MODE=0755
      # Sonarr Config
      - UN_SONARR_0_URL=http://sonarr:8989
      - UN_SONARR_0_API_KEY=[apiiii]
      - UN_SONARR_0_PATHS_0=/downloads
      - UN_SONARR_0_PROTOCOLS=torrent,usenet
      - UN_SONARR_0_TIMEOUT=10s
      - UN_SONARR_0_DELETE_ORIG=true
      - UN_SONARR_0_DELETE_DELAY=5m
      # Radarr Config
      - UN_RADARR_0_URL=http://radarr:7878
      - UN_RADARR_0_API_KEY=[apiiii]
      - UN_RADARR_0_PATHS_0=/downloads
      - UN_RADARR_0_PROTOCOLS=torrent,usenet
      - UN_RADARR_0_TIMEOUT=10s
      - UN_RADARR_0_DELETE_ORIG=true
      - UN_RADARR_0_DELETE_DELAY=5m
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: 200k
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - /mnt/hdd/data:/downloads
      
 Next, maybe the errors I'm getting?
 
```
[INFO] 2024/04/04 21:12:32 [Radarr] Completed item still waiting: home.movie.1.1995.bluray no extractable files found at: /data/downloads/user/complete/movies/home.movie.1.1995.complete.bluray (stat err: stat /data/downloads/user/complete/movies/home.movie.1.1995.complete.bluray: no such file or directory)

[INFO] 2024/04/04 21:12:32 [Radarr] Completed item still waiting: home.movie.2, no extractable files found at: /data/downloads/intermediate/home.movie.2(stat err: stat /data/downloads/intermediate/home.movie.2 no such file or directory)

[INFO] 2024/04/04 21:12:32 [Radarr] Completed item still waiting: fond.memories, no extractable files found at: /data/downloads/user/complete/movies/fond.memories stat err: stat /data/downloads/user/complete/movies/fond.memories no such file or directory)

[INFO] 2024/04/04 21:12:32 [Radarr] Completed item still waiting: wedding.day.footage no extractable files found at: /data/downloads/user/complete/movies/wedding.day.footage (stat err: stat /data/downloads/user/complete/movies/wedding.day.footage: no such file or directory)

[INFO] 2024/04/04 21:12:32 [Unpackerr] Queue: [4 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted]

[INFO] 2024/04/04 21:12:32 [Unpackerr] Totals: [0 retries] [0 finished] [0|0 webhooks] [0|0 cmdhooks] [stacks; event:0, hook:0, del:0]

[INFO] 2024/04/04 21:13:32 [Unpackerr] Queue: [4 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted]

[INFO] 2024/04/04 21:13:32 [Unpackerr] Totals: [0 retries] [0 finished] [0|0 webhooks] [0|0 cmdhooks] [stacks; event:0, hook:0, del:0]
```

It seems like unpackerr knows where to look? If I go to the directories it's saying the files don't exist, the files are there.

Any help would be appreciated.

**Comment by Masrepus** [comment]
I think you are in the wrong repo for your issue 😅 
This is unipacker, a tool for emulating windows programs, usually malware.

**Comment by JimmyBringus** [comment]
Oh my goodness. Many apologies!!!

**Comment by Masrepus** [comment]
Haha no worries, all the best for your attempts to fix your actual issues!
