### ISSUE TITLE
unipacker as I/O

### ISSUE THREAD

**Issue by garanews** [unipacker/unipacker#7]
Is possible to use unipacker to unpack packed files automatically in batch?

**Comment by Masrepus** [comment]
At the moment this is not possible, but it's a good idea. We will look into this

**Comment by garanews** [comment]
Nice.
Meanwhile I tried manually but probably I am wronging something; steps I did:
launch unipacker
press 0
passed the path of packed file (upx)
passed detect xxxx (tried singles and both possibilities)
passed aaaa
wait for the end 
the file unpacked.dump is created but is still packed...

Am I missing something?

**Comment by Masrepus** [comment]
The thing is that we dump the loaded program memory, so there is no PE file creation with section renaming etc going on. Also the original unpacking stub will also still be there. What you can do instead is statically analyze the dump. E.g. for UPX, there is one section that is filled with zeros at the beginning, which is then filled with data after unpacking. You can compare the results by calling "dump packed.dump" immediately after loading the sample. Then you can compare it with "unpacked.dump" after emulation has completed and look at the differences

**Comment by 0x6d696368** [comment]
@garanews: In addition to what @Masrepus said you could try the following Python script:
```
import pefile

pe = pefile.PE('unpacked.dump')

header_size = len(pe.header)
header_size -= header_size % -pe.OPTIONAL_HEADER.SectionAlignment # align to 4K 

pe.sections[0].PointerToRawData = header_size
# make the section 2GiB ... pefile truncates to actual max size of data
pe.sections[0].SizeOfRawData = 0x80000000
pe.sections[0].Misc_VirtualSize = len(pe.sections[0].get_data())

for section in pe.sections[1:]:
	section.SizeOfRawData = 0
	section.Misc_VirtualSize = 0

pe.write('unpacked.exe')
```

It will do a __very__ dirty fixup of the PE header, i.e., it will map the entire memory dump file via the first section of the original PE header and set the sizes of all other sections to zero.
This way static analysis gets the correct offsets when loading the so modified memory dump as a PE file. One could also unhook the imports etc. to further aid static analysis of the dump, etc.

**Comment by Masrepus** [comment]
Thanks @0x6d696368, your script really helps us with dumping the unpacked binary as a reasonable exe file!

**Comment by garanews** [comment]
Hello, I tried but still miss something:
1) started with 995d341e2ee327cf0adebd2c3e53c35e  /tmp/unipacker/Sample/UPX/honey_upx_zombie.exe  PE32 executable (DLL) (GUI) Intel 80386, for MS Windows, UPX compressed

2) generated dump with unipacker
![image](https://user-images.githubusercontent.com/16938405/53252840-22625080-36c0-11e9-8a3c-ca9545293f7d.png)
f5970705f12b80574af693ceb4f3deac  unpacked.dump   PE32 executable (DLL) (GUI) Intel 80386, for MS Windows, UPX compressed

3) tried script from @0x6d696368
![image](https://user-images.githubusercontent.com/16938405/53252879-3ad26b00-36c0-11e9-9c5d-8ac74e6ffb96.png)
9911dbfc056bfe98fecd570fab9812b8 unpacked.exe: PE32 executable (DLL) (GUI) Intel 80386, for MS Windows, UPX compressed


File seems still packed.
If I try UPX instead:
4) 
![image](https://user-images.githubusercontent.com/16938405/53253201-ff846c00-36c0-11e9-944c-b4aae503f375.png)

424702dc4fd5612e8163e6b35088de4e  honey_upx_zombie.exe  PE32 executable (DLL) (GUI) Intel 80386, for MS Windows


I was wondering to use your tool against different files packed with different packers and retrieve the PE32 unpacked (manually step by step, or automatically later on)

**Comment by Masrepus** [comment]
It is still being identified as UPX packed because the sections inside the binary are still called UPX0 and UPX1. This is likely what the "file" command checks for. The difference between the packed file and the one dumped by unipacker is that in the packed file, one section is only filled with zeros, while in the dump it now contains the actual program data. So if you use other forms of identification (Yara rules with the "yara" command or string inspection with the "strings"
