### ISSUE TITLE
|ERROR| Invalid command 'Sj' (0x53)

### ISSUE THREAD

**Issue by garanews** [unipacker/unipacker#8]
using radare2 commit: 3cde905a209a39fbc88ba03557705fb5467aff6e build: 2019-02-19__12:15:40
using r2pipe (1.2.0)
in order to be able to run your script I had to modify "Sj" to "iSj".
(it seems that iSj is for rabin)

**Comment by Masrepus** [comment]
Thank you for letting us know! We weren't aware that "Sj" had been deprecated by r2
